import { IoMdHome } from "react-icons/io";
import { FaRetweet } from "react-icons/fa";
import { FaRegUserCircle } from "react-icons/fa";
import { FaBookmark } from "react-icons/fa";
import { BsFillCameraReelsFill } from "react-icons/bs";
import { FiUsers } from "react-icons/fi";
import { FaUserEdit } from "react-icons/fa";
import { TbPlus } from "react-icons/tb";
import { BsFillPostcardHeartFill } from "react-icons/bs";
import { FaThumbsUp, FaRegEye } from "react-icons/fa";
import { FaRegHeart } from "react-icons/fa6";
import { FaRegBookmark } from "react-icons/fa";
import { IoChatboxEllipses, IoShareSocialSharp } from "react-icons/io5";
import { RxCross2 } from "react-icons/rx";
import { IoSend } from "react-icons/io5";
import { RiDeleteBin6Line } from "react-icons/ri";
import { MdEdit } from "react-icons/md";

export const HomeIcon = (props) => <IoMdHome {...props} />;
export const PostIcon = (props) => <BsFillPostcardHeartFill {...props} />;
export const TweetIcon = (props) => <FaRetweet {...props} />;
export const UsersIcon = (props) => <FiUsers {...props} />;
export const UnSaveIcon = (props) => <FaBookmark {...props} />;
export const SaveIcon = (props) => <FaRegBookmark {...props} />;
export const LikedHistoryIcon = (props) => <FaThumbsUp {...props} />;
export const WatchHistory = (props) => <FaRegEye {...props} />;
export const EditProfileIcon = (props) => <FaUserEdit {...props} />;
export const CreateContentIcon = (props) => <TbPlus {...props} />;
export const DeleteIcon = (props) => <RiDeleteBin6Line {...props} />;
export const ShareIcon = (props) => <IoShareSocialSharp {...props} />;
export const CommentIcon = (props) => <IoChatboxEllipses {...props} />;
export const LikeIcon = (props) => <FaRegHeart {...props} />;
export const ReelIcon = (props) => <BsFillCameraReelsFill {...props} />;
export const ProfileIcon = (props) => <FaRegUserCircle {...props} />;
export const EditIcon = (props) => <MdEdit {...props} />;
export const CloseIcon = (props) => <RxCross2 {...props} />;
export const SendIcon = (props) => <IoSend {...props} />;
